### ISSUE TITLE
[BUG]检查某日是否记录接口返回值为空

### ISSUE THREAD

**Issue by Jackey351** [yanfeinetworktechnology/yanfei_backend#28]
### 路由地址
/wx/record/check_recorded
### 预期是什么？
预期返回该日是否记工。
### 实际发生了什么？
实际上这一天已经记了工了，但是接口返回值为
{
  "status": 0,
  "data": null,
  "message": ""
}
### 截图

**Comment by LogicJake** [comment]
@lhd791150351 给一下具体的日期和工人id

**Comment by Jackey351** [comment]
2019-05-24
45





------------------ 原始邮件 ------------------
发件人: "Chenyang Shi"<notifications@github.com>; 
发送时间: 2019年5月24日(星期五) 晚上10:26
收件人: "yanfeinetworktechnology/yanfei_backend"<yanfei_backend@noreply.github.com>; 
抄送: "791150351"<791150351@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yanfeinetworktechnology/yanfei_backend] [BUG]检查某日是否记录接口返回值为空 (#28)




@lhd791150351 给一下具体的日期和工人id

**Comment by LogicJake** [comment]
worker_id 指定错了，worker_id应该是被记账人的id
