### ISSUE TITLE
[FEATURE]增加接口参数

### ISSUE THREAD

**Issue by Jackey351** [yanfeinetworktechnology/yanfei_backend#30]
### 涉及路由
/wx/record/add_hour_record
### 额外描述（请务必详细）
增加项目名称project_name、备注remark参数

**Comment by LogicJake** [comment]
@lhd791150351 项目名不是根据groupid获得的吗

**Comment by Jackey351** [comment]
接口是哪一个？






------------------ 原始邮件 ------------------
发件人: "Chenyang Shi"<notifications@github.com>; 
发送时间: 2019年5月24日(星期五) 晚上10:25
收件人: "yanfeinetworktechnology/yanfei_backend"<yanfei_backend@noreply.github.com>; 
抄送: "791150351"<791150351@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yanfeinetworktechnology/yanfei_backend] [FEATURE]增加接口参数 (#30)




@lhd791150351 项目名不是根据groupid获得的吗

**Comment by LogicJake** [comment]
@lhd791150351 当时说的是group是绑定项目的 所以说不需要每次都指定项目名称 记在这个group下就好了

**Comment by LogicJake** [comment]
done in 6323aa0dfe5d75e48a118c55ba7aa6ce28c28c5b
