### ISSUE TITLE
[FEATURE]不要返回id，要id返回名称

### ISSUE THREAD

**Issue by Jackey351** [yanfeinetworktechnology/yanfei_backend#34]
### 涉及路由
/wx/record/check_recorded
### 额外描述（请务必详细）
   返回值中
    "worker_id": 47,
    "group_id": 30,
不要返回id，要返回名称，因为要给检查记录的人看工人真实姓名real_name和班组名group_name

**Comment by LogicJake** [comment]
@lhd791150351 等明天吧

**Comment by Jackey351** [comment]
嗯




------------------ 原始邮件 ------------------
发件人: "Chenyang Shi"<notifications@github.com>; 
发送时间: 2019年5月25日(星期六) 晚上6:27
收件人: "yanfeinetworktechnology/yanfei_"<yanfei_backend@noreply.github.com>; 
抄送: "791150351"<791150351@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yanfeinetworktechnology/yanfei_backend] [FEATURE]不要返回id，要id返回名称 (#34)




@lhd791150351 等明天吧

**Comment by LogicJake** [comment]
@lhd791150351 新的聊天方式

**Comment by Jackey351** [comment]
666




------------------ 原始邮件 ------------------
发件人: "Chenyang Shi"<notifications@github.com>; 
发送时间: 2019年5月25日(星期六) 晚上6:28
收件人: "yanfeinetworktechnology/yanfei_"<yanfei_backend@noreply.github.com>; 
抄送: "791150351"<791150351@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yanfeinetworktechnology/yanfei_backend] [FEATURE]不要返回id，要id返回名称 (#34)




@lhd791150351 新的聊天方式

**Comment by Jackey351** [comment]
/wx/record/get_month_records这个接口也要返回类似/wx/record/check_recorded接口的详细信息


------------------ 原始邮件 ------------------
发件人: "Chenyang Shi"<notifications@github.com>;
发送时间: 2019年5月25日(星期六) 晚上6:28
收件人: "yanfeinetworktechnology/yanfei_backend"<yanfei_backend@noreply.github.com>;
抄送: "791150351"<791150351@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yanfeinetworktechnology/yanfei_backend] [FEATURE]不要返回id，要id返回名称 (#34)




@lhd791150351 新的聊天方式

**Comment by LogicJake** [comment]
@lhd791150351 了解
