### ISSUE TITLE
[FEATURE]返回数据加参数

### ISSUE THREAD

**Issue by Jackey351** [yanfeinetworktechnology/yanfei_backend#36]
### 涉及路由
/wx/record/get_month_records
### 额外描述（请务必详细）
返回数据加一个判断是工时还是分项的参数

**Comment by LogicJake** [comment]
/wx/record/get_month_records和check_recorded都添加了一个字段type，0代表工时，1代表工项。

**Comment by Jackey351** [comment]
ok




------------------ 原始邮件 ------------------
发件人: "Chenyang Shi"<notifications@github.com>; 
发送时间: 2019年5月27日(星期一) 上午9:28
收件人: "yanfeinetworktechnology/yanfei_"<yanfei_backend@noreply.github.com>; 
抄送: "791150351"<791150351@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yanfeinetworktechnology/yanfei_backend] [FEATURE]返回数据加参数 (#36)




/wx/record/get_month_records和check_recorded都添加了一个字段type，0代表工时，1代表工项。

**Comment by LogicJake** [comment]
@lhd791150351 完美
