### ISSUE TITLE
[BUG]添加记录可能需要验证存在性和判断身份

### ISSUE THREAD

**Issue by Jackey351** [yanfeinetworktechnology/yanfei_backend#39]
### 路由地址
/wx/record/add_hour_record 
/wx/record/check_recorded
### 预期是什么？
不知道这样解释对不对，不应该可以给任何一个已存在的工人添加工作记录，可能需要在添加前判断这个工人是否绑定手机号和真实姓名，而且可能需要判断身份：如果添加人是一个班组的班组长，则工人必须是本班组的成员；如果添加人是一个班组的工人，则只能给自己添加，不能给别人添加。
### 实际发生了什么？
我用工人：哈哈哈 居然可以给班组长：eqwe添加工作记录，居然也可以给一个信息全为空的人添加记录，
### 截图
![QQ截图20190527190803](https://user-images.githubusercontent.com/27855734/58416417-0ea9fa00-80b4-11e9-92d2-fd7cf8892403.png)
![QQ截图20190527190823](https://user-images.githubusercontent.com/27855734/58416423-149fdb00-80b4-11e9-9433-c2e5ca2d5f4e.png)
![QQ截图20190527191758](https://user-images.githubusercontent.com/27855734/58416472-3ef19880-80b4-11e9-8445-5a514ee503e9.png)
![QQ截图20190527191816](https://user-images.githubusercontent.com/27855734/58416474-3f8a2f00-80b4-11e9-9204-8ed6be6547de.png)

**Comment by LogicJake** [comment]
@lhd791150351 使得 现在只能勉强能用 补天计划还要进行

**Comment by LogicJake** [comment]
@lhd791150351 前面一部分不需要特别验证，因为之后我会每个接口天剑是否实名制检查，不通过的话将无法进行任务操作，也就谈不上出现在一个班组中了

**Comment by Jackey351** [comment]
好的




------------------ 原始邮件 ------------------
发件人: "Chenyang Shi"<notifications@github.com>; 
发送时间: 2019年5月27日(星期一) 晚上7:19
收件人: "yanfeinetworktechnology/yanfei_"<yanfei_backend@noreply.github.com>; 
抄送: "791150351"<791150351@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yanfeinetworktechnology/yanfei_backend] [BUG]添加记录可能需要验证存在性和判断身份 (#39)




@lhd791150351 使得 现在只能勉强能用 补天计划还要进行

**Comment by LogicJake** [comment]
@lhd791150351 此外也说明我们急需测试人员 2333
