### ISSUE TITLE
[BUG]分页获取招工信息出错

### ISSUE THREAD

**Issue by Jackey351** [yanfeinetworktechnology/yanfei_backend#4]
### 路由地址
wx/work/search?page=4&limit=8或9或10
wx/work/search?page=3&limit=11

### 预期是什么？
正常返回招工信息

### 实际发生了什么？
{
  "status": 20002,
  "message": "数据库错误"
}
### 截图
![image](https://user-images.githubusercontent.com/20673460/57577476-33925080-74aa-11e9-8f59-ef69e61b9d34.png)

**Comment by LogicJake** [comment]
fixed by 2f6ffc0f9ef28e6bccf1aef839ba74e46f5a6261
